import express from "express";
import authMiddleware from "../middleware/authMiddleware.js";
import updateUser from "../controllers/updateUser.js";
const router = express.Router();

router.put("/", authMiddleware, updateUser);
export default router;


// Swagger code is generated by GPT
// Swagger Documentation for Update User
/**
 * @swagger
 * components:
 *   schemas:
 *     UpdateUser:
 *       type: object
 *       properties:
 *         name:
 *           type: string
 *           description: Updated user name
 *         email:
 *           type: string
 *           description: Updated user email address
 *         age:
 *           type: number
 *           description: Updated user age
 *         location:
 *           type: string
 *           description: Updated user location
 *       example:
 *         name: updatedTestName
 *         email: updatedtest@gmail.com
 *         age: 25
 *         location: New York
 */

/**
 * @swagger
 * /api/v1/user:
 *   put:
 *     summary: Update user details
 *     tags:
 *       - User
 *     security:
 *       - bearerAuth: []  # Assumes JWT or similar token authentication
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/UpdateUser'
 *     responses:
 *       200:
 *         description: User updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User updated successfully
 *                 user:
 *                   $ref: '#/components/schemas/UpdateUser'
 *       400:
 *         description: Bad request, invalid input
 *       401:
 *         description: Unauthorized, token is missing or invalid
 *       500:
 *         description: Internal server error
 */